// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSI2uq0UpnSHHZFI4Nltzli9ma28SIbCU',
    appId: '1:891655798621:web:3382434b25756d02ba32b4',
    messagingSenderId: '891655798621',
    projectId: 'gala-ac239',
    authDomain: 'gala-ac239.firebaseapp.com',
    storageBucket: 'gala-ac239.firebasestorage.app',
    measurementId: 'G-LZ9E9CQTRT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHsDPOF0fsAQn_xQlIg9dqJAKiW7gbbV0',
    appId: '1:891655798621:android:4dc125c8ba2dd956ba32b4',
    messagingSenderId: '891655798621',
    projectId: 'gala-ac239',
    storageBucket: 'gala-ac239.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBycoho24TzYXFmavYbPfUDujBRcvZtO14',
    appId: '1:891655798621:ios:c10baea7148acffcba32b4',
    messagingSenderId: '891655798621',
    projectId: 'gala-ac239',
    storageBucket: 'gala-ac239.firebasestorage.app',
    iosClientId: '891655798621-uds8hkgqmuqahhgevjk2krafcetknt3r.apps.googleusercontent.com',
    iosBundleId: 'com.example.myProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBycoho24TzYXFmavYbPfUDujBRcvZtO14',
    appId: '1:891655798621:ios:c10baea7148acffcba32b4',
    messagingSenderId: '891655798621',
    projectId: 'gala-ac239',
    storageBucket: 'gala-ac239.firebasestorage.app',
    iosClientId: '891655798621-uds8hkgqmuqahhgevjk2krafcetknt3r.apps.googleusercontent.com',
    iosBundleId: 'com.example.myProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSI2uq0UpnSHHZFI4Nltzli9ma28SIbCU',
    appId: '1:891655798621:web:a401d1f7b14316faba32b4',
    messagingSenderId: '891655798621',
    projectId: 'gala-ac239',
    authDomain: 'gala-ac239.firebaseapp.com',
    storageBucket: 'gala-ac239.firebasestorage.app',
    measurementId: 'G-B7C4R4GTE0',
  );
}
