name: my_project
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  shared_preferences:
  cupertino_icons: ^1.0.8
  provider: ^6.0.5   

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  firebase_core: ^2.16.0  # Required for all Firebase services
  firebase_auth: ^4.7.1  # For Firebase Authentication (optional)
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/user.png
    - assets/naga_city.png
    - assets/pili.jpg
    - assets/siruma.jpg
    - assets/caramoan.png
    - assets/pasacao.png
    - assets/tinambac.jpg
    - assets/bg_settings.png
    - assets/fare.png
    - assets/ffchains.png
    - assets/nearby.png
    - assets/park.png
    - assets/cafe.png
    - assets/directions.png
    - assets/restaurant.png
    - assets/arco_diez.jpeg
    - assets/royaltea.png
    - assets/kape_sina_una.jpeg
    - assets/harina_cafe.jpeg
    - assets/calle_barlin.png
    - assets/bellissimo.png
    - assets/beanleaf.png
    - assets/garden_cafe.jpeg
    
