name: my_project
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^9.0.2
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  geocoding: ^2.0.5
  smooth_page_indicator: ^1.1.0

  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.8
  provider: ^6.1.2  
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  google_sign_in: ^6.3.0
  image_picker: ^0.8.7+4
   

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logoWhite.png
    - assets/Gala.png
    - assets/logo.png
    - assets/user.png
    - assets/naga_city.png
    - assets/pili.jpg
    - assets/siruma.jpg
    - assets/caramoan.png
    - assets/pasacao.png
    - assets/tinambac.jpg
    - assets/bg_settings.png
    - assets/fare.png
    - assets/ffchains.png
    - assets/nearby.png
    - assets/park.png
    - assets/cafe.png
    - assets/directions.png
    - assets/restaurant.png
    - assets/arco_diez.jpeg
    - assets/royaltea.png
    - assets/kape_sina_una.jpeg
    - assets/harina_cafe.jpeg
    - assets/harina.jpeg
    - assets/calle_barlin.png
    - assets/bellissimo.png
    - assets/tct.jpg
    - assets/beanleaf.png
    - assets/garden_cafe.jpeg
    - assets/login_background.png
    - assets/google_icon.png
    - assets/onboarding1.png
    - assets/onboarding2.png
    - assets/bg2.png
    - assets/onboarding3.png
    - assets/blueloc.png
    - assets/allow_loc.png
    - assets/success.png
    - assets/images/arco_diez.jpg
    - assets/images/tung.png
    - assets/images/bomb.png
    - assets/images/fsq.png
    - assets/images/google.png
    - assets/images/fb.png
    - assets/fonts/
    - assets/images/
    - assets/icons/

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter_24pt-Regular.ttf
        - asset: assets/fonts/Inter_28pt-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter_24pt-SemiBold.ttf
          weight: 600
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
    